// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57qpEUUxSxsPjrHrbl7iQxGqOidX-YH0',
    appId: '1:399634297260:web:cf3f63be4d720b8e3b8a09',
    messagingSenderId: '399634297260',
    projectId: 'cdpc-dd-b3b46',
    authDomain: 'cdpc-dd-b3b46.firebaseapp.com',
    storageBucket: 'cdpc-dd-b3b46.firebasestorage.app',
    measurementId: 'G-SJ81LQG826',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0Mm7nuRtMfkFbO5capSkZfMT4amHJIs',
    appId: '1:399634297260:android:e865049dc97024c03b8a09',
    messagingSenderId: '399634297260',
    projectId: 'cdpc-dd-b3b46',
    storageBucket: 'cdpc-dd-b3b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRWATwrbOdqmWaHp78eToJVAygHPJ6Ek',
    appId: '1:399634297260:ios:26edd0889a7ed9e33b8a09',
    messagingSenderId: '399634297260',
    projectId: 'cdpc-dd-b3b46',
    storageBucket: 'cdpc-dd-b3b46.firebasestorage.app',
    iosBundleId: 'com.example.cdpcTnp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRWATwrbOdqmWaHp78eToJVAygHPJ6Ek',
    appId: '1:399634297260:ios:26edd0889a7ed9e33b8a09',
    messagingSenderId: '399634297260',
    projectId: 'cdpc-dd-b3b46',
    storageBucket: 'cdpc-dd-b3b46.firebasestorage.app',
    iosBundleId: 'com.example.cdpcTnp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA57qpEUUxSxsPjrHrbl7iQxGqOidX-YH0',
    appId: '1:399634297260:web:34d7b1bb82992cb63b8a09',
    messagingSenderId: '399634297260',
    projectId: 'cdpc-dd-b3b46',
    authDomain: 'cdpc-dd-b3b46.firebaseapp.com',
    storageBucket: 'cdpc-dd-b3b46.firebasestorage.app',
    measurementId: 'G-HVKBWN7J0N',
  );
}